version: "3"
services:
  mongo:
    build: ./mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGO_INITDB_DATABASE: blockchain-indexer
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
volumes:
  mongodb_data:
