version: "3"
services:
  mongo:
    build: ./mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGO_INITDB_DATABASE: blockchain-indexer
      MONGO_REPLICA_HOST: mongo
      MONGO_REPLICA_PORT: 27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/blockchain-indexer --quiet
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - indexer_network
    volumes:
      - ./mongodb/data:/data/db

  indexer:
    build:
      context: .
      dockerfile: ./apps/indexer/Dockerfile
    environment:
      DATABASE_URL: mongodb://root:prisma@mongo:27017/blockchain-indexer?authSource=admin&directConnection=true
    networks:
      - indexer_network
    depends_on:
      mongo:
        condition: service_healthy

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - indexer_network
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongodb_data:
  indexer_data:

networks:
  indexer_network:
    driver: bridge
